- hosts: linux
  vars:
    training:
      topic: ansible
      trainer: sathish
      labs: aws
  tasks:
  - name: print dict varaiable
    debug:
      msg: "keys {{ item.key }} and value is {{ item.value }}"
    with_dict: "{{ training }}"
