- hosts: linux
  ignore_errors: yes
  tasks:
  - name: print command output
    command: echo " i am in ansible training"
    register: output
  - debug: msg="standard output={{output.stdout}}"
  - debug: msg="standard error={{output.stderr}}"
